### ISSUE TITLE
NoSuchMethodException when running from JAR

### ISSUE THREAD

**Issue by sylvainhalle** [liflab/labpal#11]
There's something wrong with the build script. Running from Eclipse is OK, but calling the plots page when running from a compiled jar leads to:

```
java.lang.NoSuchMethodError: ca.uqac.lif.labpal.table.Table.getDataTable()Lca/uqac/lif/labpal/table/DataTable;
	at ca.uqac.lif.labpal.plot.gnuplot.Scatterplot.toGnuplot(Scatterplot.java:130)
	at ca.uqac.lif.labpal.plot.gnuplot.GnuPlot.toGnuplot(GnuPlot.java:90)
	at ca.uqac.lif.labpal.plot.gnuplot.GnuPlot.getImage(GnuPlot.java:107)
	at ca.uqac.lif.labpal.plot.Plot.getImage(Plot.java:321)
```

**Comment by sylvainhalle** [comment]
...and the method *does* exist, if you look at the source.

**Comment by sylvainhalle** [comment]
It happens if the lab's build script's dependency is not set to the latest version of LabPal. Compiling it will overwrite whatever newer labpal.jar you have with that one every time.
