### ISSUE TITLE
Bug in PiePlot

### ISSUE THREAD

**Issue by sylvainhalle** [liflab/labpal#38]
Try to show the third plot in BrowserLab. You get this:

```
java.lang.ClassCastException: ca.uqac.lif.mtnp.table.PrimitiveValue cannot be cast to java.lang.Number
	at de.erichseifert.gral.plots.PiePlot$PiePlotLegend.getEntries(SourceFile:783)
	at de.erichseifert.gral.plots.legends.AbstractLegend.add(SourceFile:275)
	at de.erichseifert.gral.plots.legends.ValueLegend.add(SourceFile:86)
	at de.erichseifert.gral.plots.AbstractPlot.add(SourceFile:581)
	at de.erichseifert.gral.plots.PiePlot.add(SourceFile:917)
	at de.erichseifert.gral.plots.AbstractPlot.add(SourceFile:564)
	at de.erichseifert.gral.plots.AbstractPlot.add(SourceFile:554)
	at de.erichseifert.gral.plots.PiePlot.(SourceFile:854)
	at ca.uqac.lif.mtnp.plot.gral.PieChart.getPlot(PieChart.java:42)
	at ca.uqac.lif.mtnp.plot.gral.GralPlot.getPlot(GralPlot.java:119)
	at ca.uqac.lif.mtnp.plot.gral.GralPlot.getImage(GralPlot.java:87)
	at ca.uqac.lif.mtnp.plot.Plot.getImage(Plot.java:311)
	at ca.uqac.lif.labpal.server.PlotImageCallback.process(PlotImageCallback.java:93)
	at ca.uqac.lif.jerrydog.Server.handle(Server.java:252)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:431)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:396)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sylvainhalle** [comment]
Actually this is a bug in MTNP, not in LabPal
