### ISSUE TITLE
Loading labs does not work

### ISSUE THREAD

**Issue by sylvainhalle** [liflab/labpal#56]
```
Exception in thread "main" java.lang.NullPointerException
	at pattheminer.MainLab.setup(MainLab.java:124)
	at ca.uqac.lif.labpal.Laboratory.loadFromJson(Laboratory.java:651)
	at ca.uqac.lif.labpal.Laboratory.loadFromString(Laboratory.java:634)
	at ca.uqac.lif.labpal.Laboratory.loadFromZip(Laboratory.java:760)
	at ca.uqac.lif.labpal.Laboratory.loadFromFilename(Laboratory.java:791)
	at ca.uqac.lif.labpal.Laboratory.initialize(Laboratory.java:943)
	at ca.uqac.lif.labpal.Laboratory.initialize(Laboratory.java:891)
	at pattheminer.MainLab.main(MainLab.java:525)
```

**Comment by sylvainhalle** [comment]
Closed by 4ab32cf11d6e9fade0f772ef8d906cb1e23fd4a4
