### ISSUE TITLE
Zip lab contents and allow upload of zip file

### ISSUE THREAD

**Issue by sylvainhalle** [liflab/labpal#8]

**Comment by ameadev** [comment]
To realize this functionality, I have added a new attribute that will contain the download directory of your browser. This attribute will be configured in the lab setup method as
Public void setup () {
// TODO Auto-generated method stub
setDownloadsUrl ( "/ Users / blabla / Downloads");
}

**Comment by sylvainhalle** [comment]
@ameadev When I try to upload a zip, I get this error:

```
java.lang.NullPointerException
	at ca.uqac.lif.labpal.server.UploadCallback.process(UploadCallback.java:107)
	at ca.uqac.lif.jerrydog.Server.handle(Server.java:252)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:431)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:396)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sylvainhalle** [comment]
I don't understand why you need to specify the absolute location of a folder on the user's computer for this feature to work. This cannot be a reasonable solution, as you'll need to change the lab's setup for every computer on which you'll want to run it...

**Comment by sylvainhalle** [comment]
OK, I understand what's happening. When you upload a file, the lab only looks at the filename, and then tries to read a file with that name that is supposed to be present in some hard-coded directory on the local machine. So you don't read the file that is actually being uploaded.

The expected solution is that the lab reads the file that is contained *within the POST request*, unzips it in memory, and then parses the JSON that it contains.
